[profile.default]
solc = "0.8.17"
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

[etherscan]
base-goerli = { key = "PLACEHOLDER_STRING", url = "https://api-goerli.basescan.org/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
